name: grab_lints
description: Lint rules to warn you about common misuse of Grab and fix it quickly.
version: 0.4.0
repository: https://github.com/kaboc/grab-lints

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.2.0
  custom_lint_builder: ^0.5.7

dev_dependencies:
  lints: ^3.0.0
