name: grab_lints
description: Lint rules to help avoid common misuse of Grab.
version: 0.3.2
repository: https://github.com/kaboc/grab-lints

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.2.0
  custom_lint_builder: ^0.5.3

dev_dependencies:
  lints: ^2.1.1
