name: grab_lints
description: A Dart analyzer plugin to add lint rules for Grab.
version: 0.2.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.2.0
  custom_lint_builder: ^0.5.2

dependency_overrides:
  lints: ^2.1.1
